-- Seed verified resources from research (June 27, 2026)
-- International NGOs
insert into public.resources (name, type, url, instagram, city, country, description_es, description_en, contact, verified, earthquake_specific) values
(
  'Cruz Roja Venezolana / IFRC',
  'ngo',
  'https://www.ifrc.org/press-release/venezuela-red-cross-responds-needs-emerge-aftermath-powerful-back-back-earthquakes',
  null,
  'Caracas',
  'VE',
  'Cruz Roja Venezolana desplegada en hospitales y rescates. IFRC lanzó llamamiento de emergencia para asistir a 300.000 personas con 17 toneladas de carga humanitaria.',
  'Venezuelan Red Cross deployed at hospitals and rescue sites. IFRC launched emergency appeal to assist 300,000 people; 17 tonnes dispatched.',
  'cruzrojavenezolana.org | Dona en ifrc.org/donate',
  true,
  true
),
(
  'Cruz Roja Española — Ayuda Terremoto Venezuela',
  'ngo',
  'https://www2.cruzroja.es/-/ayuda-terremoto-venezuela-2026',
  null,
  'Madrid',
  'ES',
  'Cruz Roja Española apoya a la Cruz Roja Venezolana. Acepta donaciones por Bizum código 33512 y SMS.',
  'Spanish Red Cross supporting Venezuelan Red Cross. Bizum code 33512. SMS: VENEZUELA to 38092 (€6).',
  'Bizum: 33512 | SMS: VENEZUELA al 38092 (€6) | informa@cruzroja.es',
  true,
  true
),
(
  'UNICEF — Emergencia Terremoto Venezuela',
  'ngo',
  'https://www.unicef.org/emergencies/venezuela-earthquakes',
  null,
  null,
  'INT',
  'UNICEF coordinando respuesta para 3,9 millones de niños. Asignó $2,5M. Entrega kits médicos, agua y espacios seguros. 48 toneladas de suministros en camino.',
  'UNICEF coordinating response for 3.9M children. $2.5M allocated. Delivering medical kits, water purification, child-friendly spaces. 48 MT supplies en route.',
  'unicef.org | unicefusa.org',
  true,
  true
),
(
  'Save the Children — Terremoto Venezuela 2026',
  'ngo',
  'https://www.savethechildren.es/donacion-ong/terremoto-en-venezuela-2026',
  null,
  null,
  'INT',
  'Asistiendo a 200.000 personas incluyendo 100.000 niños. Bizum España código 13132.',
  'Targeting 200,000 people including 100,000 children. Spain donations: Bizum 13132.',
  'savethechildren.es | Bizum España: 13132',
  true,
  true
),
(
  'ACNUR / UNHCR — Venezuela Earthquake Response',
  'ngo',
  'https://www.unhcr.org/us/news/briefing-notes/unhcr-rushing-support-venezuela-after-deadly-earthquakes',
  null,
  null,
  'INT',
  'ACNUR movilizando personal y suministros de emergencia. Refugio, necesidades básicas y protección.',
  'UNHCR mobilizing staff and emergency supplies. Shelter, basic necessities, and protection services.',
  'acnur.org | unrefugees.org',
  true,
  true
),
(
  'MSF / Médicos Sin Fronteras',
  'ngo',
  'https://www.msf.org',
  null,
  'Caracas',
  'VE',
  'Equipos en Caracas evaluando situación y donando kits de trauma a hospitales de Caracas y La Guaira.',
  'Teams in Caracas donating emergency trauma kits to hospitals in Caracas and La Guaira.',
  'msf.org',
  true,
  true
),
(
  'Cáritas Española — Venezuela',
  'ngo',
  'https://www.caritas.es/emergencias/caritas-con-venezuela/',
  null,
  'Madrid',
  'ES',
  'Movilizó €300.000 para Cáritas Venezuela. Bizum 00089, Santander ES23 0049 1892 6927 1329 3362.',
  'Mobilised €300,000 for Cáritas Venezuela. Bizum 00089.',
  'Bizum: 00089 | Santander: ES23 0049 1892 6927 1329 3362 | CaixaBank: ES89 2100 5731 7102 0022 7540',
  true,
  true
),
(
  'Plan International — Venezuela Earthquake Appeal',
  'ngo',
  'https://plan-international.org/get-involved/venezuela-earthquake-appeal/',
  null,
  null,
  'INT',
  'Trabajando con socios locales para asistir a niños y familias afectadas.',
  'Working with local partners to assist affected children and families.',
  'plan-international.org',
  true,
  true
),
(
  'IRC — International Rescue Committee',
  'ngo',
  'https://www.rescue.org/article/how-help-survivors-earthquakes-venezuela',
  null,
  null,
  'INT',
  'Escalando servicios para supervivientes. Lleva desde 2021 en Venezuela; asistió a 75.000 personas en 2025.',
  'Scaling services for survivors. Operating in Venezuela since 2021, reaching 75,000 people in 2025.',
  'rescue.org',
  true,
  true
),
(
  'World Central Kitchen — Venezuela',
  'ngo',
  'https://wck.org/relief/caracas-venezuela-earthquakes-2026/',
  null,
  'Caracas',
  'VE',
  'Equipo desplegado sirviendo comidas calientes. Chef José Andrés comprometió $1 millón. Bizum España: 03843.',
  'Team deployed serving hot meals. Chef José Andrés pledged $1M. Spain Bizum: 03843.',
  'wck.org | Bizum España: 03843',
  true,
  true
),
(
  'Direct Relief — Venezuela Earthquakes 2026',
  'ngo',
  'https://www.directrelief.org/emergency/venezuela-earthquakes-2026/',
  null,
  null,
  'INT',
  'Desplegando suministros médicos: kits de heridas, material quirúrgico, antibióticos. 100% de donaciones van a Venezuela.',
  'Deploying emergency medical supplies: wound care, surgical supplies, antibiotics. 100% of donations to Venezuela.',
  'directrelief.org',
  true,
  true
),
(
  'GlobalGiving — Venezuela Earthquake Relief Fund',
  'campaign',
  'https://www.globalgiving.org/projects/venezuela-earthquake-relief-fund/',
  null,
  null,
  'INT',
  'Fondo que canaliza donaciones a organizaciones locales verificadas para atención médica, rescate, refugio y agua.',
  'Fund channelling to vetted local organisations for emergency medical care, rescue, shelter and water.',
  'globalgiving.org',
  true,
  true
),
(
  'GoFundMe — We Love Foundation (Venezuela)',
  'campaign',
  'https://www.gofundme.com/f/emergency-relief-for-venezuela-earthquake-victims',
  null,
  null,
  'INT',
  '13 años de trayectoria. Más de $1 millón recaudado. 100% para víctimas del terremoto a través de socios verificados.',
  '13-year track record. Over $1M raised. 100% for earthquake victims via verified nonprofit partners.',
  'gofundme.com/f/emergency-relief-for-venezuela-earthquake-victims',
  true,
  true
),
(
  'CADENA',
  'ngo',
  'https://donate.cadena.ngo/campaign/815508/donate',
  '@cadena_org',
  null,
  'INT',
  'Organización humanitaria internacional movilizada en Venezuela para entrega directa de ayuda.',
  'International humanitarian emergency response organisation deployed in Venezuela for direct aid delivery.',
  'cadena.ngo | Instagram: @cadena_org',
  true,
  true
),
(
  'Aid for Life — Venezuela Emergency Response',
  'ngo',
  'https://aidforlifeintl.org/venezuela-earthquake-emergency-response-2026/',
  null,
  null,
  'INT',
  'Trabaja con organizaciones locales y universidades. Alimentos, agua limpia y suministros médicos.',
  'Works with local organisations and universities. Food, clean water and medical supplies.',
  'aidforlifeintl.org',
  true,
  true
),
(
  'Oxfam — Venezuela Earthquake Response',
  'ngo',
  'https://give.oxfamamerica.org/page/26493/donate/1',
  null,
  null,
  'INT',
  'Apoyando respuesta humanitaria liderada localmente en Venezuela.',
  'Supporting locally-led humanitarian response in Venezuela.',
  'oxfamamerica.org',
  true,
  true
),
(
  'The House Project — Fundación Ricardo Montaner',
  'ngo',
  'https://thehouse-project.org',
  null,
  null,
  'INT',
  'Casi 20 años de trayectoria. Ayuda directa a familias, personas sin hogar y limpieza de escombros.',
  'Nearly 20 years active. Direct aid to homeless, families and debris clearing.',
  'thehouse-project.org',
  true,
  true
),
(
  'VACC Foundation',
  'ngo',
  'https://vaccfoundation.org/donate-now/',
  null,
  null,
  'INT',
  'Canaliza recursos hacia alimentos, agua, medicamentos y refugios para familias afectadas.',
  'Channelling resources for food, water, medicine and temporary shelter for affected families.',
  'vaccfoundation.org',
  true,
  true
),
-- Spain-based collection points and coordinators
(
  'SOS Venezuela Barcelona / Meals4Hope',
  'ngo',
  'https://sosterremoto.meals4hope.org',
  '@sosvenezuelabcn',
  'Barcelona',
  'ES',
  'Plataforma de más de una docena de entidades venezolanas en Barcelona. Convierte donaciones en alimentos y medicamentos distribuidos en Venezuela. Ayuntamiento de Barcelona aportó €300.000.',
  'Platform of over a dozen Venezuelan diaspora entities in Barcelona. Converts donations to food and medicine. Barcelona City Hall contributed €300,000.',
  'sosterremoto.meals4hope.org | Instagram: @sosvenezuelabcn',
  true,
  true
),
(
  'VIDES — Voluntariado Internacional',
  'ngo',
  'https://www.vides.es/emergencia-terremoto-en-venezuela/',
  '@videsongd',
  'Madrid',
  'ES',
  'ONG salesiana en Aragón, Valencia y Cataluña. Bizum 01015. Apoya a hermanas salesianas en Venezuela.',
  'Salesian NGO in Aragón, Valencia and Catalonia. Bizum 01015. Supports Salesian sisters in Venezuela.',
  'Bizum: 01015 | BBVA: ES76 0182 3191 8502 0166 9499 | vides@vides.es | Instagram: @videsongd',
  true,
  true
),
(
  'Venezuelanos por España',
  'volunteer_coordinator',
  null,
  null,
  'Madrid',
  'ES',
  'Plataforma de venezolanos en España (26.000+ seguidores) organizando recogida de suministros en Madrid.',
  'Venezuelan community platform in Spain (26,000+ followers) organising supply collections in Madrid.',
  'Facebook: @venezolanosporespana',
  true,
  true
),
(
  'Diaspora Venezolana en Baleares — @venbalears',
  'volunteer_coordinator',
  null,
  '@venbalears',
  'Palma de Mallorca',
  'ES',
  'Comunidad venezolana en Baleares coordinando donaciones monetarias enviadas a centros de acopio en Caracas.',
  'Venezuelan community in the Balearic Islands coordinating monetary donations sent to Caracas collection centres.',
  'Instagram: @venbalears',
  true,
  true
),
(
  'diasporavenezolana.net',
  'portal',
  'https://diasporavenezolana.net',
  null,
  'Madrid',
  'ES',
  'Portal de información humanitaria y directorio de organizaciones verificadas donde donar.',
  'Humanitarian information portal and directory of vetted organisations to donate to.',
  'diasporavenezolana.net',
  true,
  true
),
(
  'Punto de recogida — Sambil Madrid (Leganés)',
  'collection_point',
  null,
  null,
  'Madrid',
  'ES',
  'Planta 0 del Sambil Madrid, Leganés. Sáb-Dom 10:00-18:30. Comida no perecedera, medicamentos, higiene, ropa, mantas.',
  'Ground floor, Sambil Madrid shopping centre, Leganés. Sat-Sun 10:00-18:30. Non-perishable food, medicine, hygiene, clothing, blankets.',
  'Sambil Madrid, Planta 0, Leganés, Madrid',
  true,
  true
),
(
  'Punto de recogida — Calle Matilde Landa 26, Madrid',
  'collection_point',
  null,
  null,
  'Madrid',
  'ES',
  'Calle Matilde Landa 26 (Metro Ventilla). Sáb-Dom 11:00-18:00 (27-28 jun 2026). Refugiados Sin Fronteras y Diáspora en Movimiento.',
  'Calle Matilde Landa 26 (Ventilla metro). Sat-Sun 11:00-18:00 (June 27-28 2026). Refugees Without Borders and Diaspora in Movement.',
  'Calle Matilde Landa, 26, Madrid (Metro Ventilla)',
  true,
  true
),
-- Venezuela-based resources
(
  'Yummy SOS',
  'portal',
  'https://sos.yummyrides.com/',
  null,
  'Caracas',
  'VE',
  'Plataforma de la app Yummy: reportar daños estructurales, trayectos gratuitos para emergencias, telemedicina gratis, directorio de refugios y seguimiento sísmico.',
  'Yummy ride-sharing platform: structural damage reporting, free rides for emergency workers, free telemedicine, shelter directory, live seismic tracking.',
  'sos.yummyrides.com',
  true,
  true
),
(
  'Desaparecidos Terremoto Venezuela',
  'missing_persons',
  'https://desaparecidosterremotovenezuela.com',
  null,
  null,
  'VE',
  'Plataforma ciudadana para reportar y buscar desaparecidos por el terremoto.',
  'Citizen platform to report and find persons missing due to the earthquake.',
  'desaparecidosterremotovenezuela.com',
  true,
  true
),
(
  'Venezuela Te Busca',
  'missing_persons',
  'https://venezuelatebusca.com',
  null,
  null,
  'VE',
  'Plataforma para buscar desaparecidos tras el terremoto.',
  'Platform for searching for missing persons after the earthquake.',
  'venezuelatebusca.com',
  true,
  true
),
(
  'Ayudandito',
  'volunteer_coordinator',
  null,
  '@ayudanditoo',
  'La Guaira',
  'VE',
  'Iniciativa local en La Guaira entregando suministros directamente. Necesita vehículos 4x4, voluntarios y suministros médicos. Acepta Zelle.',
  'Local initiative in La Guaira delivering supplies directly to affected areas. Needs 4x4 vehicles, volunteers and medical supplies. Accepts Zelle.',
  'Zelle: egarban97@gmail.com | Instagram: @ayudanditoo',
  true,
  true
),
(
  'Sun.Risas Foundation',
  'ngo',
  'https://fundraise.sunrisas.org/campaign/815513/donate',
  '@sun.risas',
  'Valencia',
  'VE',
  'Con sede en Valencia, Estado Carabobo. Recoge palas, linternas, pilas, guantes y artículos de primera necesidad.',
  'Based in Valencia, Carabobo State. Collecting shovels, flashlights, batteries, gloves and basic necessities.',
  'fundraise.sunrisas.org | Instagram: @sun.risas',
  true,
  true
),
(
  'PsicoData Venezuela',
  'psychological',
  null,
  '@psicodatavzla',
  null,
  'VE',
  'Atención psicológica gratuita para personas afectadas. Líneas directas: 0414-121 78 82 / 0424-172 39 81.',
  'Free psychological support for earthquake-affected people. Helplines: 0414-121 78 82 / 0424-172 39 81.',
  '0414-121 78 82 | 0424-172 39 81 | Instagram: @psicodatavzla',
  true,
  true
),
(
  'Grupo Venemergencia',
  'medical',
  null,
  '@venemergencia',
  null,
  'VE',
  'Plataforma médica venezolana con apoyo físico y psicológico para afectados.',
  'Venezuelan medical platform providing physical and psychological support to affected people.',
  'Instagram: @venemergencia',
  true,
  true
),
(
  'RemittVen — Transferencias sin comisión',
  'other',
  null,
  '@remittven',
  null,
  'INT',
  'Servicio de transferencias de dinero a Venezuela sin comisiones durante la emergencia del terremoto.',
  'Money transfer service to Venezuela with zero commissions during the earthquake emergency.',
  'Instagram: @remittven',
  true,
  true
);
