-- Instagram volunteer coordinators from Wave 1 research (June 27, 2026)
insert into public.resources (name, type, url, instagram, city, country, description_es, description_en, contact, verified, earthquake_specific) values
(
  'Danny Ocean — Coordinación de desaparecidos',
  'volunteer_coordinator',
  'https://www.instagram.com/dannocean/',
  '@dannocean',
  'Miami',
  'INT',
  'Convirtió su cuenta en un hub de coordinación de desaparecidos. Publicó 7 listas de pacientes hospitalizados separados de su familia. Millones de seguidores.',
  'Turned his account into a missing-persons coordination hub. Published 7 handwritten lists of hospitalised patients. Millions of followers.',
  'Instagram: @dannocean',
  true,
  true
),
(
  'Lele Pons — Coordinación de ayuda',
  'volunteer_coordinator',
  'https://www.instagram.com/lelepons/',
  '@lelepons',
  null,
  'INT',
  '52M de seguidores. Pidió a venezolanos en el terreno publicar su ubicación exacta. Compartió listas de desaparecidos de Danny Ocean.',
  '52M followers. Asked Venezuelans on the ground to post exact locations needing aid. Reshared missing-persons lists.',
  'Instagram: @lelepons',
  true,
  true
),
(
  'Carlos Baute — Ayuda desde España',
  'volunteer_coordinator',
  'https://www.instagram.com/carlos_baute/',
  '@carlos_baute',
  'Madrid',
  'ES',
  'Cantor venezolano en Madrid. Compartió contactos de emergencia, información de refugios y coordinación de recursos desde España. 1M seguidores.',
  'Venezuelan singer in Madrid. Shared emergency contacts, shelter information and resource coordination from Spain. 1M followers.',
  'Instagram: @carlos_baute',
  true,
  true
),
(
  'Sascha Fitness (Sascha Barboza)',
  'volunteer_coordinator',
  'https://www.instagram.com/saschafitness/',
  '@saschafitness',
  null,
  'INT',
  'Compartió búsquedas de personas desaparecidas, información de donaciones y actualizaciones. 6M seguidores.',
  'Shared missing person searches, donation information and updates. 6M followers.',
  'Instagram: @saschafitness',
  true,
  true
),
(
  'Bomberos Unidos Sin Fronteras',
  'volunteer_coordinator',
  'https://www.instagram.com/bomberos_unidos/',
  '@bomberos_unidos',
  'Madrid',
  'ES',
  'ONG española que desplegó 13 especialistas a Venezuela: equipos caninos, técnicos en derrumbes, sanitarios y personal médico.',
  'Spanish NGO deployed 13 specialists to Venezuela: canine search teams, debris technicians, sanitation and medical personnel.',
  'Instagram: @bomberos_unidos',
  true,
  true
),
(
  'Comando #ConVzla — María Corina Machado',
  'volunteer_coordinator',
  'https://www.instagram.com/convzlacomando/',
  '@convzlacomando',
  null,
  'VE',
  'Red nacional en Venezuela con centros de acopio en múltiples estados: Aragua, Carabobo y otros. 2M seguidores.',
  'National network in Venezuela with collection centres in multiple states: Aragua, Carabobo and others. 2M followers.',
  'Instagram: @convzlacomando',
  true,
  true
),
(
  'Global Empowerment Mission (GEM)',
  'ngo',
  'https://www.instagram.com/globalempowermentmission/',
  '@globalempowermentmission',
  'Miami',
  'INT',
  'Comprometió $10M iniciales. Equipos de reconocimiento y respuesta desplegados en Venezuela. 515K seguidores.',
  'Committed initial $10M in aid. Reconnaissance and response teams deployed in Venezuela. 515K followers.',
  'Instagram: @globalempowermentmission | gem.ngo',
  true,
  true
),
(
  'We Love Foundation',
  'ngo',
  'https://www.instagram.com/welove_foundation/',
  '@welove_foundation',
  'Miami',
  'INT',
  'Antigua I Love Venezuela Foundation (13 años). Coordina cadena de suministros a Venezuela junto con GEM y Cáritas.',
  'Formerly I Love Venezuela Foundation (13 years). Coordinating supply chain into Venezuela with GEM and Cáritas.',
  'Instagram: @welove_foundation | gofundme.com/f/emergency-relief-for-venezuela-earthquake-victims',
  true,
  true
),
(
  'CADENA — Ayuda Venezuela',
  'ngo',
  'https://www.instagram.com/cadena_ac/',
  '@cadena_ac',
  'México',
  'LATAM',
  'ONG humanitaria internacional. Anunció en Instagram su despliegue a Venezuela. Acepta donaciones bancarias por Instagram.',
  'International humanitarian NGO. Announced via Instagram it is deploying to Venezuela. Accepts bank donations via Instagram.',
  'Instagram: @cadena_ac | donate.cadena.ngo',
  true,
  true
),
(
  'Aqui Brando — Coordinador desde España',
  'volunteer_coordinator',
  'https://www.instagram.com/aquibrando/',
  '@aquibrando',
  'España',
  'ES',
  'Creador de contenido venezolano en España. Habilitó sus redes para coordinar ayuda humanitaria, localizar desaparecidos y compartir puntos de recogida.',
  'Venezuelan content creator in Spain. Opened his networks to coordinate humanitarian aid, find missing persons and share collection points.',
  'Instagram: @aquibrando',
  true,
  true
),
(
  'SOS Venezuela Barcelona (@sosvenezuelabcn)',
  'volunteer_coordinator',
  'https://www.instagram.com/sosvenezuelabcn/',
  '@sosvenezuelabcn',
  'Barcelona',
  'ES',
  'Más de 12 entidades venezolanas en Cataluña unidas: Asocaven, Pejucat, Meals4Hope, Ensamble de Cuatros, Asociación Ayuda Venezuela. Donaciones monetarias prioritarias.',
  'Over 12 Venezuelan diaspora entities in Catalonia: Asocaven, Pejucat, Meals4Hope, Ensamble de Cuatros, Asociación Ayuda Venezuela. Monetary donations prioritised.',
  'Instagram: @sosvenezuelabcn | sosterremoto.meals4hope.org',
  true,
  true
),
(
  'Venezolanos en España — Comunidades',
  'volunteer_coordinator',
  'https://www.instagram.com/venezolanos_en_espana/',
  '@venezolanos_en_espana',
  'España',
  'ES',
  'Cuenta comunitaria de venezolanos en España. Comparte información sobre puntos de recogida, donaciones y solidaridad con Venezuela.',
  'Venezuelan community account in Spain. Shares information on collection points, donations and solidarity with Venezuela.',
  'Instagram: @venezolanos_en_espana',
  true,
  true
),
(
  'Venezolanas en Europa',
  'volunteer_coordinator',
  'https://www.instagram.com/venezolanaseneuropa/',
  '@venezolanaseneuropa',
  'Europa',
  'ES',
  'Cuenta de venezolanas en Europa coordinando información sobre ayuda solidaria desde España y otros países europeos.',
  'Venezuelan women community account in Europe coordinating solidarity aid information from Spain and other European countries.',
  'Instagram: @venezolanaseneuropa',
  true,
  true
),
(
  'Catherine Fulop — Coordinadora desde Argentina',
  'volunteer_coordinator',
  'https://www.instagram.com/fulopcatherine/',
  '@fulopcatherine',
  'Buenos Aires',
  'LATAM',
  'Actriz venezolana en Argentina. Compartió el GoFundMe de We Love Foundation, información de desaparecidos y campañas de donación.',
  'Venezuelan actress in Argentina. Shared We Love Foundation GoFundMe, missing persons info and donation campaigns.',
  'Instagram: @fulopcatherine',
  true,
  true
),
(
  'Healing Venezuela',
  'medical',
  'https://healingvenezuela.org/',
  '@healingvenezuela',
  'Londres',
  'INT',
  'ONG con sede en UK. Provee apoyo médico al sistema de salud venezolano. Activa en respuesta al terremoto.',
  'UK-based NGO providing medical support to Venezuela''s health system. Active in earthquake response.',
  'healingvenezuela.org | Instagram: @healingvenezuela',
  true,
  true
);
